[config]

# =============================================================================
# 2. System Components (Wayland, Bars, Notifications)
# =============================================================================

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-dark-colors.rasi'
output_path = '~/.config/rofi/rofi-dark-colors.rasi'

[templates.eww]
input_path = '~/.config/matugen/templates/eww-colors.scss'
output_path = '~/.config/eww/colors.scss'

#[templates.ags]
#input_path = '~/.config/matugen/templates/ags-colors.scss'
#output_path = '~/ags/colors.scss'

# =============================================================================
# 3. Applications (Terminals, Editors, Browsers)
# =============================================================================

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/kitty-colors.conf'
post_hook = '''
  pkill -SIGUSR1 -x kitty || :
'''

[templates.yazi]
input_path  = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship/starship.toml'

#[templates.lush]
#input_path = '~/.config/matugen/templates/lush-colors.json'
#output_path = '~/.config/nvim/colors/lush-colors.json'

[templates.neovim]
input_path  = '~/.config/matugen/templates/nvim-colors.lua'
output_path = '~/.config/nvim/generated.lua'
post_hook   = '''
  pkill -SIGUSR1 -x nvim || :
'''
