-- Generated by matugen. Manual changes will be overwritten.
-- Source: /home/lyxsly/wallpapers/p3r-wallpaper2.jpg

local colors = {}


colors.background = "rgba(19120cff)"

colors.error = "rgba(ffb4abff)"

colors.error_container = "rgba(93000aff)"

colors.inverse_on_surface = "rgba(372f28ff)"

colors.inverse_primary = "rgba(87521aff)"

colors.inverse_surface = "rgba(efe0d5ff)"

colors.on_background = "rgba(efe0d5ff)"

colors.on_error = "rgba(690005ff)"

colors.on_error_container = "rgba(ffdad6ff)"

colors.on_primary = "rgba(4b2800ff)"

colors.on_primary_container = "rgba(ffdcc0ff)"

colors.on_primary_fixed = "rgba(2d1600ff)"

colors.on_primary_fixed_variant = "rgba(6a3b02ff)"

colors.on_secondary = "rgba(412c19ff)"

colors.on_secondary_container = "rgba(ffdcc0ff)"

colors.on_secondary_fixed = "rgba(291806ff)"

colors.on_secondary_fixed_variant = "rgba(59422dff)"

colors.on_surface = "rgba(efe0d5ff)"

colors.on_surface_variant = "rgba(d5c3b6ff)"

colors.on_tertiary = "rgba(2c340fff)"

colors.on_tertiary_container = "rgba(dee8b3ff)"

colors.on_tertiary_fixed = "rgba(171e00ff)"

colors.on_tertiary_fixed_variant = "rgba(424a23ff)"

colors.outline = "rgba(9e8e82ff)"

colors.outline_variant = "rgba(51443aff)"

colors.primary = "rgba(feb877ff)"

colors.primary_container = "rgba(6a3b02ff)"

colors.primary_fixed = "rgba(ffdcc0ff)"

colors.primary_fixed_dim = "rgba(feb877ff)"

colors.scrim = "rgba(000000ff)"

colors.secondary = "rgba(e2c0a4ff)"

colors.secondary_container = "rgba(59422dff)"

colors.secondary_fixed = "rgba(ffdcc0ff)"

colors.secondary_fixed_dim = "rgba(e2c0a4ff)"

colors.shadow = "rgba(000000ff)"

colors.source_color = "rgba(805f41ff)"

colors.surface = "rgba(19120cff)"

colors.surface_bright = "rgba(403730ff)"

colors.surface_container = "rgba(261e18ff)"

colors.surface_container_high = "rgba(312822ff)"

colors.surface_container_highest = "rgba(3c332cff)"

colors.surface_container_low = "rgba(221a14ff)"

colors.surface_container_lowest = "rgba(130d07ff)"

colors.surface_dim = "rgba(19120cff)"

colors.surface_tint = "rgba(feb877ff)"

colors.surface_variant = "rgba(51443aff)"

colors.tertiary = "rgba(c2cc99ff)"

colors.tertiary_container = "rgba(424a23ff)"

colors.tertiary_fixed = "rgba(dee8b3ff)"

colors.tertiary_fixed_dim = "rgba(c2cc99ff)"


colors.active_border = "rgba(805f41ff)"
colors.inactive_border = "rgba(51443a88)"

return colors
