-- Generated by matugen. Manual changes will be overwritten.
-- Source: /home/lyxsly/wallpapers/siteharu.png

local colors = {}


colors.background = "rgba(101417ff)"

colors.error = "rgba(ffb4abff)"

colors.error_container = "rgba(93000aff)"

colors.inverse_on_surface = "rgba(2d3135ff)"

colors.inverse_primary = "rgba(226488ff)"

colors.inverse_surface = "rgba(dfe3e7ff)"

colors.on_background = "rgba(dfe3e7ff)"

colors.on_error = "rgba(690005ff)"

colors.on_error_container = "rgba(ffdad6ff)"

colors.on_primary = "rgba(00344cff)"

colors.on_primary_container = "rgba(c7e7ffff)"

colors.on_primary_fixed = "rgba(001e2eff)"

colors.on_primary_fixed_variant = "rgba(004c6cff)"

colors.on_secondary = "rgba(21323eff)"

colors.on_secondary_container = "rgba(d2e5f5ff)"

colors.on_secondary_fixed = "rgba(0b1d29ff)"

colors.on_secondary_fixed_variant = "rgba(374955ff)"

colors.on_surface = "rgba(dfe3e7ff)"

colors.on_surface_variant = "rgba(c1c7ceff)"

colors.on_tertiary = "rgba(342b4bff)"

colors.on_tertiary_container = "rgba(e8ddffff)"

colors.on_tertiary_fixed = "rgba(1e1635ff)"

colors.on_tertiary_fixed_variant = "rgba(4b4263ff)"

colors.outline = "rgba(8b9198ff)"

colors.outline_variant = "rgba(41484dff)"

colors.primary = "rgba(93cdf6ff)"

colors.primary_container = "rgba(004c6cff)"

colors.primary_fixed = "rgba(c7e7ffff)"

colors.primary_fixed_dim = "rgba(93cdf6ff)"

colors.scrim = "rgba(000000ff)"

colors.secondary = "rgba(b6c9d8ff)"

colors.secondary_container = "rgba(374955ff)"

colors.secondary_fixed = "rgba(d2e5f5ff)"

colors.secondary_fixed_dim = "rgba(b6c9d8ff)"

colors.shadow = "rgba(000000ff)"

colors.source_color = "rgba(7991a3ff)"

colors.surface = "rgba(101417ff)"

colors.surface_bright = "rgba(353a3dff)"

colors.surface_container = "rgba(1c2024ff)"

colors.surface_container_high = "rgba(262a2eff)"

colors.surface_container_highest = "rgba(313539ff)"

colors.surface_container_low = "rgba(181c20ff)"

colors.surface_container_lowest = "rgba(0a0f12ff)"

colors.surface_dim = "rgba(101417ff)"

colors.surface_tint = "rgba(93cdf6ff)"

colors.surface_variant = "rgba(41484dff)"

colors.tertiary = "rgba(cdc0e9ff)"

colors.tertiary_container = "rgba(4b4263ff)"

colors.tertiary_fixed = "rgba(e8ddffff)"

colors.tertiary_fixed_dim = "rgba(cdc0e9ff)"


colors.active_border = "rgba(7991a3ff)"
colors.inactive_border = "rgba(41484d88)"

return colors
