-- Generated by matugen. Manual changes will be overwritten.
-- Source: {{image}}

local colors = {}

<* for name, value in colors *>
colors.{{name}} = "rgba({{value.default.hex_stripped}}ff)"
<* endfor *>

colors.active_border = "rgba({{colors.source_color.default.hex_stripped}}ff)"
colors.inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}88)"

return colors
